### PR TITLE
add card with API

### PR DESCRIPTION
**Pull request by Hamza-Luciano**

### CODE REVIEW

**Review by mastemm — APPROVED** [review]
looks good for me

**Review by mastemm — DISMISSED** [review]

**Review by mastemm — DISMISSED** [review]
conflicts resolved

**Review by LuigiMenez — DISMISSED** [review]
Ok for me

**Review by LoicBrassart — DISMISSED** [review]
Saw no Evil

**Review by LuigiMenez — CHANGES_REQUESTED** [review]
No validate for Scrum master

**Review by mastemm — APPROVED** [review]

**Review by LuigiMenez — APPROVED** [review]
Ok for me

**Review by LoicBrassart — APPROVED** [review]
Saw no Evil

**Pull request merged**
